---
resolver: lts-20.23

packages:
  - .
  - xmobar
  - xmonad
  - xmonad-contrib

flags:
  xmonad-contrib:
    use_xft: true
  xmobar:
    with_mpd: true
    with_threaded: true
    with_xft: true
    with_xpm: true
