---
resolver: lts-15.3

packages:
    - .
    - xmobar
    - xmonad
    - xmonad-contrib

flags:
    xmobar:
        with_mpd: true
        with_threaded: true
        with_xft: true
        with_xpm: true
