---
resolver: lts-22.33

packages:
  - .
  - xmobar
  - xmonad
  - xmonad-contrib

extra-deps:
  - libmpd-0.10.0.1

flags:
  xmonad-contrib:
    use_xft: true
  xmobar:
    with_mpd: true
    with_threaded: true
    with_xft: true
    with_xpm: true
